---
- name: ssh play book
  hosts: '{{ target_host | default("all") }}'
  gather_facts: no
  tasks:
    - name: push ansible pub key
      authorized_key:
        user: "{{ ansible_user | default('root')}}"
        state: present
        key: "{{ lookup('file', item) }}"
      with_items:
        - '~/.ssh/ansible_key.pub'